services:
  db:
    image: postgres:15
    container_name: nko_bot_postgres
    environment:
      POSTGRES_DB: nko_bot_db
      POSTGRES_USER: nko_user
      POSTGRES_PASSWORD: nko_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nko_user -d nko_bot_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  app:
    build: .
    container_name: nko_bot_app
    command: ["python", "app/run_bot_with_init.py"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://nko_user:nko_pass@db:5432/nko_bot_db
    volumes:
      - .:/code

  # api:
  #   build: .
  #   container_name: nko_bot_api
  #   command: ["python", "app/cli/run_api.py"]
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: postgresql+asyncpg://nko_user:nko_pass@db:5432/nko_bot_db
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/code

  # admin-panel:
  #   build: ./nko-admin-panel
  #   container_name: nko_admin_panel
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - ./nko-admin-panel:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   command: npm start

volumes:
  postgres_data: