from datetime import datetime
from equipment import Equipment, RentalStatus

# ---------- Справочники ----------
CITIES = [
    {"id": 1, "name": "Москва"},
    {"id": 2, "name": "Санкт-Петербург"},
    {"id": 3, "name": "Екатеринбург"},
    {"id": 4, "name": "Казань"},
    {"id": 5, "name": "Новосибирск"},
    {"id": 6, "name": "Нижний Новгород"},
    {"id": 7, "name": "Ростов-на-Дону"},
    {"id": 8, "name": "Самара"},
    {"id": 9, "name": "Воронеж"},
    {"id": 10, "name": "Пермь"},
]

LANDLORDS = [
    {"id": 1, "name": "Иван Петров", "username": "ivanp"},
    {"id": 2, "name": "Анна Смирнова", "username": "annasm"},
    {"id": 3, "name": "Дмитрий Соколов", "username": "dimas"},
    {"id": 4, "name": "Мария Иванова", "username": "masha"},
    {"id": 5, "name": "Олег Кузнецов", "username": "olegk"},
]

CATEGORIES = [
    {"id": 1, "name": "звук"},
    {"id": 2, "name": "свет"},
    {"id": 3, "name": "мебель"},
]

# ---------- Мокап оборудования ----------
MOCK_EQUIPMENT = [
    Equipment(
        id=1,
        name="Микшер Yamaha MG10XU",
        city_id=CITIES[0]["id"],
        landlord_id=LANDLORDS[0]["id"],
        status=RentalStatus.AVAILABLE,
        photo_url="tg://photo/1",
        category_id=CATEGORIES[0]["id"],
        is_approved=True,
        description="10-канальный аналоговый микшер с эффектами.",
        quantity=1,
        created_at=datetime(2025, 1, 1, 12, 0, 0),
    ),
    Equipment(
        id=2,
        name="Сабвуфер JBL PRX818XLF",
        city_id=CITIES[1]["id"],
        landlord_id=LANDLORDS[0]["id"],
        status=RentalStatus.BOOKED,
        photo_url="tg://photo/2",
        category_id=CATEGORIES[0]["id"],
        is_approved=False,
        description="18\" активный сабвуфер.",
        quantity=2,
        created_at=datetime(2025, 1, 2, 12, 0, 0),
    ),
    Equipment(
        id=3,
        name="Светодиодный прожектор Chauvet DJ SlimPAR 56",
        city_id=CITIES[2]["id"],
        landlord_id=LANDLORDS[1]["id"],
        status=RentalStatus.AVAILABLE,
        photo_url="/img/slimpar56.jpg",
        category_id=CATEGORIES[1]["id"],
        is_approved=True,
        description="Компактный RGB прожектор, DMX.",
        quantity=8,
        created_at=datetime(2025, 1, 3, 12, 0, 0),
    ),
    Equipment(
        id=4,
        name="Стойка для микрофона K&M 210/9",
        city_id=CITIES[3]["id"],
        landlord_id=LANDLORDS[1]["id"],
        status=RentalStatus.RETURNED,
        photo_url=None,
        category_id=CATEGORIES[2]["id"],
        is_approved=True,
        description="Телескопическая стойка, классика сцены.",
        quantity=6,
        created_at=datetime(2025, 1, 4, 12, 0, 0),
    ),
    Equipment(
        id=5,
        name="LED панель Godox LEDP120C",
        city_id=CITIES[4]["id"],
        landlord_id=LANDLORDS[1]["id"],
        status=RentalStatus.IN_USE,
        photo_url="tg://photo/5",
        category_id=CATEGORIES[1]["id"],
        is_approved=False,
        description="Биколор панель для интервью.",
        quantity=3,
        created_at=datetime(2025, 1, 5, 12, 0, 0),
    ),
    Equipment(
        id=6,
        name="Стул складной Икеа",
        city_id=CITIES[5]["id"],
        landlord_id=LANDLORDS[2]["id"],
        status=RentalStatus.AVAILABLE,
        photo_url="/img/chair.jpg",
        category_id=CATEGORIES[2]["id"],
        is_approved=True,
        description="Простой складной стул для зрителей.",
        quantity=40,
        created_at=datetime(2025, 1, 6, 12, 0, 0),
    ),
    Equipment(
        id=7,
        name="DMX Controller 192",
        city_id=CITIES[6]["id"],
        landlord_id=LANDLORDS[2]["id"],
        status=RentalStatus.AVAILABLE,
        photo_url=None,
        category_id=CATEGORIES[1]["id"],
        is_approved=False,
        description="Базовый контроллер на 192 канала.",
        quantity=1,
        created_at=datetime(2025, 1, 7, 12, 0, 0),
    ),
    Equipment(
        id=8,
        name="RCF ART 712-A (активная колонка)",
        city_id=CITIES[7]["id"],
        landlord_id=LANDLORDS[3]["id"],
        status=RentalStatus.BOOKED,
        photo_url="tg://photo/8",
        category_id=CATEGORIES[0]["id"],
        is_approved=True,
        description="700W, 12\" драйвер, ровный звук.",
        quantity=2,
        created_at=datetime(2025, 1, 8, 12, 0, 0),
    ),
    Equipment(
        id=9,
        name="Диван двухместный",
        city_id=CITIES[8]["id"],
        landlord_id=LANDLORDS[4]["id"],
        status=RentalStatus.IN_USE,
        photo_url="/img/sofa2.jpg",
        category_id=CATEGORIES[2]["id"],
        is_approved=False,
        description="Комфорт для лаунж-зоны или гримёрки.",
        quantity=1,
        created_at=datetime(2025, 1, 9, 12, 0, 0),
    ),
    Equipment(
        id=10,
        name="Световая стойка с диммером",
        city_id=CITIES[9]["id"],
        landlord_id=LANDLORDS[4]["id"],
        status=RentalStatus.RETURNED,
        photo_url=None,
        category_id=CATEGORIES[1]["id"],
        is_approved=True,
        description="Стойка + диммерный блок на 4 канала.",
        quantity=2,
        created_at=datetime(2025, 1, 10, 12, 0, 0),
    ),
]